name: Deploy Unity WebGL to GitHub Pages

on:
  push:
    branches:
      - main  # Passe diesen Branch an, falls notwendig

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true  # Aktiviert Git LFS

      - name: Set up Unity
        uses: game-ci/unity-setup@v2
        with:
          unityVersion: 2021.3.0f1  # Ersetze dies durch deine Unity-Version

      - name: Build Unity project
        run: |
          xvfb-run --auto-servernum --server-args='-screen 0 640x480x24' \
          /opt/unity/Editor/Unity \
          -projectPath . \
          -quit \
          -batchmode \
          -buildTarget WebGL \
          -executeMethod BuildScript.BuildWebGL \
          -logFile /dev/stdout

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL  # Passe dies an den Pfad an, wohin der Unity-Build ausgegeben wird