name: Build and Deploy Unity WebGL to GitHub Pages

on:
  push:
    branches:
      - main  # Passe den Branch an, falls nötig

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true  # Aktiviert Git LFS

      - name: Cache Unity packages
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ runner.os }}-

      - name: Install Unity and Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}  # Lizenzdatei aus GitHub Secrets
        with:
          unityVersion: 2022.3.9f1  # Setze deine Unity-Version
          targetPlatform: WebGL
          projectPath: .  # Setze das Projektverzeichnis auf das Wurzelverzeichnis
          buildsPath: build/WebGL  # Der Pfad, wo die Builds gespeichert werden

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/WebGL  # Passe dies an den Output-Pfad an, wohin der Unity-Build ausgegeben wird